services:
  db:
    build:
      dockerfile: Dockerfile.pgvector
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file: .env
    environment:
      POSTGRES_HOST: db
    ports:
      - "8000:8000"

volumes:
  postgres_data: { }
