[project]
name = "hwp-qna-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.66",
    "bs4>=0.0.2",
    "celery[redis]>=5.5.3",
    "datetime>=5.5",
    "fastapi[standard]>=0.120.3",
    "jpype1>=1.6.0",
    "langchain>=1.0.8",
    "langchain-ollama>=1.0.0",
    "langchain-postgres>=0.0.16",
    "langchain-text-splitters>=1.0.0",
    "pandas>=2.3.3",
    "pgvector<0.4",
    "psycopg[binary]>=3.2.12",
    "pwdlib[argon2]>=0.3.0",
    "pydantic>=2.12.3",
    "pydantic-settings>=2.11.0",
    "pyjwt>=2.10.1",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "s3path>=0.6.4",
    "sqlmodel>=0.0.27",
    "tqdm>=4.67.1",
    "uuid>=1.30",
]

[dependency-groups]
lint = [
    "boto3-stubs[ec2,s3]>=1.40.70",
    "celery-types>=0.23.0",
    "pandas-stubs>=2.3.2.250926",
    "ruff>=0.14.3",
]


[tool.basedpyright]
pythonVersion = "3.13"
reportUnusedImport = false
reportUnusedVariable = false
executionEnvironments = [
    { root = "app" }
]

[tool.ruff.lint.isort]
# 섹션 순서 정의
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]

known-first-party = [
    "api",
    "core",
    "db",
    "errors",
    "models",
    "schemas",
    "services",
    "utils",
]

lines-between-types = 1
lines-after-imports = 2
force-sort-within-sections = true
split-on-trailing-comma = true
